# ─────────────────────────────────────────────────────────────────────────────
# Chess Reps — SvelteKit application
#
# Multi-stage build. Two stages keep the final image small:
#
#   Stage 1 (builder) — installs ALL dependencies including build tools,
#   compiles the better-sqlite3 native addon, and runs `vite build`.
#
#   Stage 2 (runner) — copies only what is needed to run the app: the
#   compiled build output, the production node_modules (with the pre-built
#   native addon already inside), and the database migration files.
#
# Why two stages?
#   better-sqlite3 is a native C++ Node.js addon. Compiling it requires Python,
#   make, and a C++ compiler — roughly 200MB of build tools. Those tools are
#   needed only at build time. Multi-stage builds let us discard them before
#   creating the final image, resulting in a significantly smaller image.
# ─────────────────────────────────────────────────────────────────────────────


# ── Stage 1: Build ────────────────────────────────────────────────────────────
FROM node:22-alpine AS builder

# Build tools required to compile better-sqlite3 from source.
# These are NOT needed in the final runtime image.
RUN apk add --no-cache python3 make g++

WORKDIR /app

# Copy package files first. Docker caches each layer — if package.json and
# package-lock.json have not changed, the `npm ci` layer is served from cache
# on subsequent builds, saving several minutes.
COPY package.json package-lock.json ./

# npm ci = clean install from the exact versions in package-lock.json.
# Preferred over `npm install` in CI/CD and Docker builds for reproducibility.
RUN npm ci

# Copy the rest of the source. This happens after npm ci so that changing a
# source file does not invalidate the node_modules cache layer.
COPY . .

# Build the SvelteKit app. With adapter-node, the output lands in /app/build.
# build/index.js is the Node.js HTTP server entrypoint.
RUN npm run build

# Remove devDependencies in-place so we can copy a leaner node_modules to the
# runner stage. Production deps only (better-sqlite3, drizzle-orm, bcryptjs).
RUN npm prune --omit=dev


# ── Stage 2: Production runtime ───────────────────────────────────────────────
FROM node:22-alpine AS runner

# better-sqlite3's compiled .node file links against libstdc++ at runtime.
# This is a small shared library — not the full compiler toolchain.
RUN apk add --no-cache libstdc++

WORKDIR /app

# Copy the pruned production node_modules from the builder stage.
# The compiled better-sqlite3 native binary is already inside here.
COPY --from=builder /app/node_modules ./node_modules

# Copy the compiled SvelteKit app.
COPY --from=builder /app/build ./build

# Copy the Drizzle migration files. The app runs these automatically on startup
# to create tables on first run and apply new migrations on upgrades.
COPY --from=builder /app/drizzle ./drizzle

# Copy package.json. Node.js needs it to understand this is an ES module
# project ("type": "module" in package.json).
COPY --from=builder /app/package.json ./

# Create the data directory where the SQLite file will live.
# In production this is overwritten by the Docker volume mount, but it must
# exist so the container starts cleanly even without a volume.
RUN mkdir -p /app/data

# Tell Node.js and SvelteKit this is a production environment.
ENV NODE_ENV=production

# The port the Node.js HTTP server listens on. adapter-node reads this env var.
# Must match the port mapping in docker-compose.yml.
ENV PORT=3000

# Document the port — does not actually publish it (docker-compose does that).
EXPOSE 3000

# Health check — Docker polls this to know whether the container is healthy.
# Waits 30s for the app to start, then checks every 30s.
# The /api/health endpoint returns 200 + JSON and requires no authentication.
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
    CMD wget -qO- http://localhost:3000/api/health || exit 1

# Start the Node.js server. build/index.js is generated by adapter-node.
CMD ["node", "build/index.js"]
