-- Seed: Alapin Sicilian mainline — 1.e4 c5 2.c3 d5
--
-- FEN strings generated by Chess.js, not calculated by hand.
-- Chess.js 1.x omits the en passant square when no enemy pawn can capture it,
-- which is why all positions here use '-' for the en passant field.

-- 1. e4  (from starting position)
INSERT INTO book_move (from_fen, to_fen, san, annotation, contributor) VALUES (
    'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1',
    'e4',
    'Alapin Sicilian — move 1',
    'seed'
);
--> statement-breakpoint
-- 1... c5  (Sicilian Defence)
INSERT INTO book_move (from_fen, to_fen, san, annotation, contributor) VALUES (
    'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1',
    'rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
    'c5',
    'Alapin Sicilian — move 1',
    'seed'
);
--> statement-breakpoint
-- 2. c3  (Alapin variation — white's defining move)
INSERT INTO book_move (from_fen, to_fen, san, annotation, contributor) VALUES (
    'rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2',
    'rnbqkbnr/pp1ppppp/8/2p5/4P3/2P5/PP1P1PPP/RNBQKBNR b KQkq - 0 2',
    'c3',
    'Alapin Sicilian — the Alapin move',
    'seed'
);
--> statement-breakpoint
-- 2... d5  (main line response — central counter-attack)
INSERT INTO book_move (from_fen, to_fen, san, annotation, contributor) VALUES (
    'rnbqkbnr/pp1ppppp/8/2p5/4P3/2P5/PP1P1PPP/RNBQKBNR b KQkq - 0 2',
    'rnbqkbnr/pp2pppp/8/2pp4/4P3/2P5/PP1P1PPP/RNBQKBNR w KQkq - 0 3',
    'd5',
    'Alapin Sicilian — main line',
    'seed'
);
